const topicsList = [
  {
    children: [
      {
        name: 'Software',
        topicID: 'topics_technology_software',
        icon: 'bolt',
        color: 'yellow',
        image: 'https://unsplash.com/photos/466ENaLuhLY'
      },
      {
        name: 'Game Dev',
        topicID: 'topics_technology_gamedev',
        icon: 'bolt',
        color: 'yellow',
        image: 'https://unsplash.com/photos/XC3fq-ffXRI'
      },
      {
        name: 'Web Dev',
        topicID: 'topics_technology_webdev',
        icon: 'bolt',
        color: 'yellow',
        image: 'https://unsplash.com/photos/OqtafYT5kTw'
      },
      {
        name: 'Mobile Dev',
        topicID: 'topics_technology_mobiledev',
        icon: 'bolt',
        color: 'yellow',
        image: 'https://unsplash.com/photos/89xuP-XmyrA'
      },
      {
        name: 'Backend Dev',
        topicID: 'topics_technology_backenddev',
        icon: 'bolt',
        color: 'yellow',
        image: 'https://unsplash.com/photos/1K6IQsQbizI'
      },
      {
        name: 'Electronics',
        topicID: 'topics_technology_electronics',
        icon: 'bolt',
        color: 'yellow',
        image: 'https://unsplash.com/photos/SYTO3xs06fU' ,
      },
      {
        name: 'Hardware',
        topicID: 'topics_technology_hardware',
        icon: 'bolt',
        color: 'yellow',
        image: 'https://unsplash.com/photos/ogxlyCA1BQc' ,
      },
      {
        name: 'Semiconductors',
        topicID: 'topics_technology_semiconductors',
        icon: 'bolt',
        color: 'yellow',
        image: 'https://unsplash.com/photos/c3ZWXOv1Ndc' ,
      },
      {
        name: 'Cloud Computing',
        topicID: 'topics_technology_cloudcomputing',
        icon: 'bolt',
        color: 'yellow',
        image: 'https://unsplash.com/photos/aWslrFhs1w4' ,
      },
      {
        name: 'VR/AR',
        topicID: 'topics_technology_vrar',
        icon: 'bolt',
        color: 'yellow',
        image: 'https://unsplash.com/photos/IMUwe-p1yqs' ,
      },
      {
        name: 'Crypto',
        topicID: 'topics_technology_crypto',
        icon: 'bolt',
        color: 'yellow',
        image: 'https://unsplash.com/photos/aX1hN4uNd-I' ,
      },
      {
        name: 'AI',
        topicID: 'topics_technology_ai',
        icon: 'bolt',
        color: 'yellow',
        image: 'https://unsplash.com/photos/U3sOwViXhkY' ,
      },
      {
        name: 'Automation',
        topicID: 'topics_technology_automation',
        icon: 'bolt',
        color: 'yellow',
        image: 'https://unsplash.com/photos/GpNOhig3LSU' ,
      },
      {
        name: 'IT & Networking',
        topicID: 'topics_technology_itnetworking',
        icon: 'bolt',
        color: 'yellow',
        image: 'https://unsplash.com/photos/zFYUsLk_50Y' ,
      },
      {
        name: 'Aerospace & Aviation',
        topicID: 'topics_technology_aerospaceaviation',
        icon: 'bolt',
        color: 'yellow',
        image: 'https://unsplash.com/photos/Ptd-iTdrCJM' ,
      },
      {
        name: 'Automotive',
        topicID: 'topics_technology_automotive',
        icon: 'bolt',
        color: 'yellow',
        image: 'https://unsplash.com/photos/Lz53HpZkt_Q' ,
      },
    ],
    name: 'Technology',
    topicID: 'topics_technology',
    icon: 'bolt',
    color: 'yellow',
    image: 'https://unsplash.com/photos/iar-afB0QQw' ,
  },
  {
    children: [
      {
        name: 'Physics',
        topicID: 'topics_science_physics',
        icon: 'atom',
        color: 'purple',
        image: 'https://unsplash.com/photos/Y31Z6Mf7rys' ,
      },
      {
        name: 'Biotechnology',
        topicID: 'topics_science_biotechnology',
        icon: 'atom',
        color: 'purple',
        image: 'https://unsplash.com/photos/L7en7Lb-Ovc' ,
      },
      {
        name: 'Astrophysics',
        topicID: 'topics_science_astrophysics',
        icon: 'atom',
        color: 'purple',
        image: 'https://unsplash.com/photos/n00dm9FBwrs' ,
      },
      {
        name: 'Chemistry',
        topicID: 'topics_science_chemistry',
        icon: 'atom',
        color: 'purple',
        image: 'https://unsplash.com/photos/yS3XM9qx3hQ' ,
      },
      {
        name: 'Biology',
        topicID: 'topics_science_biology',
        icon: 'atom',
        color: 'purple',
        image: 'https://unsplash.com/photos/biVuafyC8oI' ,
      },
      {
        name: 'Anthropology',
        topicID: 'topics_science_anthropology',
        icon: 'atom',
        color: 'purple',
        image: 'https://unsplash.com/photos/ZZV1FOGaQ8s' ,
      },
      {
        name: 'Renewable Energy',
        topicID: 'topics_science_renewableenergy',
        icon: 'atom',
        color: 'purple',
        image: 'https://unsplash.com/photos/eIBTh5DXW9w' ,
      },
    ],
    name: 'Science',
    topicID: 'topics_science',
    icon: 'atom',
    color: 'purple',
    image: 'https://unsplash.com/photos/OgvqXGL7XO4' ,
  },
  {
    children: [
      {
        name: 'Photography',
        topicID: 'topics_creatives_photography',
        icon: 'palette',
        color: 'green',
        image: 'https://unsplash.com/photos/2Wv9VnwzeeI' ,
      },
      {
        name: 'Videography',
        topicID: 'topics_creatives_videography',
        icon: 'palette',
        color: 'green',
        image: 'https://unsplash.com/photos/hlKw49XvyRU' ,
      },
      {
        name: 'UI/UX',
        topicID: 'topics_creatives_uiux',
        icon: 'palette',
        color: 'green',
        image: 'https://unsplash.com/photos/cZr2sgaxy3Q' ,
      },
      {
        name: 'Graphic Design',
        topicID: 'topics_creatives_graphicdesign',
        icon: 'palette',
        color: 'green',
        image: 'https://unsplash.com/photos/muOHbrFGEQY' ,
      },
      {
        name: 'Visual Art',
        topicID: 'topics_creatives_visualart',
        icon: 'palette',
        color: 'green',
        image: 'https://unsplash.com/photos/MigkcNowxQk' ,
      },
      {
        name: 'Fashion & Apparel',
        topicID: 'topics_creatives_fashionapparel',
        icon: 'palette',
        color: 'green',
        image: '',
      },
    ],
    name: 'Creatives',
    topicID: 'topics_creatives',
    icon: 'palette',
    color: 'green',
    image: 'https://unsplash.com/photos/5E5N49RWtbA' ,
  },
  {
    children: [
      {
        name: 'Music',
        topicID: 'topics_entertainment_music',
        icon: 'film',
        color: 'orange',
        image: 'https://unsplash.com/photos/1oKxSKSOowE' ,
      },
      {
        name: 'Acting',
        topicID: 'topics_entertainment_acting',
        icon: 'film',
        color: 'orange',
        image: 'https://unsplash.com/photos/Hn3S90f6aak' ,
      },
      {
        name: 'Comedy',
        topicID: 'topics_entertainment_comedy',
        icon: 'film',
        color: 'orange',
        image: 'https://unsplash.com/photos/9oFQ_CCCBa0' ,
      },
      {
        name: 'Motion Picture',
        topicID: 'topics_entertainment_motionpicture',
        icon: 'film',
        color: 'orange',
        image: 'https://unsplash.com/photos/j6PStH6cuRY' ,
      },
      {
        name: 'Writing',
        topicID: 'topics_entertainment_writing',
        icon: 'film',
        color: 'orange',
        image: 'https://unsplash.com/photos/y02jEX_B0O0' ,
      },
      {
        name: 'Gaming',
        topicID: 'topics_entertainment_gaming',
        icon: 'film',
        color: 'orange',
        image: 'https://unsplash.com/photos/m3hn2Kn5Bns' ,
      },
    ],
    name: 'Entertainment',
    topicID: 'topics_entertainment',
    icon: 'film',
    color: 'orange',
    image: 'https://unsplash.com/photos/9lTUAlNB87M' ,
  },
  {
    children: [
      {
        name: 'Entrepreneurship',
        topicID: 'topics_business_entrepreneurship',
        icon: 'user-tie',
        color: 'black',
        image: 'https://unsplash.com/photos/jw3GOzxiSkw' ,
      },
      {
        name: 'Small Business',
        topicID: 'topics_business_smallbusiness',
        icon: 'user-tie',
        color: 'black',
        image: 'https://unsplash.com/photos/qvWnGmoTbik' ,
      },
      {
        name: 'Large Business',
        topicID: 'topics_business_largebusiness',
        icon: 'user-tie',
        color: 'black',
        image: 'https://unsplash.com/photos/Iboom5tbfvs' ,
      },
      {
        name: 'Startups',
        topicID: 'topics_business_startups',
        icon: 'user-tie',
        color: 'black',
        image: 'https://unsplash.com/photos/Y_LgXwQEx2c' ,
      },
      {
        name: 'HR',
        topicID: 'topics_business_hr',
        icon: 'user-tie',
        color: 'black',
        image: 'https://unsplash.com/photos/kOuCX7fh50U' ,
      },
      {
        name: 'Accounting',
        topicID: 'topics_business_accounting',
        icon: 'user-tie',
        color: 'black',
        image: 'https://unsplash.com/photos/kAJLRQwt5yY' ,
      },
      {
        name: 'Logistics',
        topicID: 'topics_business_logistics',
        icon: 'user-tie',
        color: 'black',
        image: 'https://unsplash.com/photos/uBe2mknURG4' ,
      },
      {
        name: 'Manufacturing',
        topicID: 'topics_business_manufacturing',
        icon: 'user-tie',
        color: 'black',
        image: 'https://unsplash.com/photos/xoxnfVIE7Qw' ,
      },
      {
        name: 'Sales',
        topicID: 'topics_business_sales',
        icon: 'user-tie',
        color: 'black',
        image: 'https://unsplash.com/photos/VrJnsLH2nOY' ,
      },
      {
        name: 'Operations',
        topicID: 'topics_business_operations',
        icon: 'user-tie',
        color: 'black',
        image: 'https://unsplash.com/photos/gcsNOsPEXfs' ,
      },
      {
        name: 'Management',
        topicID: 'topics_business_management',
        icon: 'user-tie',
        color: 'black',
        image: 'https://unsplash.com/photos/5aiRb5f464A' ,
      },
    ],
    name: 'Business',
    topicID: 'topics_business',
    icon: 'user-tie',
    color: 'black',
    image: 'https://unsplash.com/photos/ZGjbiukp_-A' ,
  },
  {
    children: [
      {
        name: 'Stock Market',
        topicID: 'topics_finance_stockmarket',
        icon: 'chart-line',
        color: 'green',
        image: 'https://unsplash.com/photos/9lI7KVWXVX0' ,
      },
      {
        name: 'Day Trading',
        topicID: 'topics_finance_daytrading',
        icon: 'chart-line',
        color: 'green',
        image: 'https://unsplash.com/photos/N__BnvQ_w18' ,
      },
      {
        name: 'Wealth Management',
        topicID: 'topics_finance_wealthmanagement',
        icon: 'chart-line',
        color: 'green',
        image: 'https://unsplash.com/photos/cEukkv42O40' ,
      },
      {
        name: 'Banking',
        topicID: 'topics_finance_banking',
        icon: 'chart-line',
        color: 'green',
        image: 'https://unsplash.com/photos/lhltMGdohc8' ,
      },
      {
        name: 'Insurance',
        topicID: 'topics_finance_insurance',
        icon: 'chart-line',
        color: 'green',
        image: 'https://unsplash.com/photos/oRYOOjvPq8E' ,
      },
    ],
    name: 'Finance & Markets',
    topicID: 'topics_finance',
    icon: 'chart-line',
    color: 'green',
    image: 'https://unsplash.com/photos/1M4wYTqVD4o' ,
  },
  {
    children: [
      {
        name: 'Social Media Marketing',
        topicID: 'topics_marketing_socialmediamarketing',
        icon: 'hashtag',
        color: 'twitterBlue',
        image: 'https://unsplash.com/photos/xv7-GlvBLFw' ,
      },
      {
        name: 'Advertising',
        topicID: 'topics_marketing_advertising',
        icon: 'hashtag',
        color: 'twitterBlue',
        image: 'https://unsplash.com/photos/5r5554u-mHo' ,
      },
      {
        name: 'Branding',
        topicID: 'topics_marketing_branding',
        icon: 'hashtag',
        color: 'twitterBlue',
        image: 'https://unsplash.com/photos/wwqRpSNBPq4' ,
      },
    ],
    name: 'Marketing',
    topicID: 'topics_marketing',
    icon: 'hashtag',
    color: 'twitterBlue',
    image: 'https://unsplash.com/photos/bLY5JqP_Ldw' ,
  },
  {
    children: [
      {
        name: 'Fitness',
        topicID: 'topics_health_fitness',
        icon: 'heartbeat',
        color: 'red',
        image: 'https://unsplash.com/photos/lTkF2Tdx9uI' ,
      },
      {
        name: 'Nutrition',
        topicID: 'topics_health_nutrition',
        icon: 'heartbeat',
        color: 'red',
        image: 'https://unsplash.com/photos/4_jhDO54BYg' ,
      },
      {
        name: 'Running',
        topicID: 'topics_health_running',
        icon: 'heartbeat',
        color: 'red',
        image: 'https://unsplash.com/photos/QVD3Xht9txA' ,
      },
      {
        name: 'Crossfit',
        topicID: 'topics_health_crossfit',
        icon: 'heartbeat',
        color: 'red',
        image: 'https://unsplash.com/photos/WIPIAJW2-P8' ,
      },
      {
        name: 'Weight Lifting',
        topicID: 'topics_health_weightlifting',
        icon: 'heartbeat',
        color: 'red',
        image: 'https://unsplash.com/photos/79nVN_Cmj3o' ,
      },
      {
        name: 'Medicine',
        topicID: 'topics_health_medicine',
        icon: 'heartbeat',
        color: 'red',
        image: 'https://unsplash.com/photos/kfJkpeI6Lgc' ,
      },
      {
        name: 'Physical Therapy',
        topicID: 'topics_health_physicaltherapy',
        icon: 'heartbeat',
        color: 'red',
        image: 'https://unsplash.com/photos/o6jUolZ7QJk' ,
      },
    ],
    name: 'Health & Wellness',
    topicID: 'topics_health',
    icon: 'heartbeat',
    color: 'red',
    image: 'https://unsplash.com/photos/vnpTRdmtQ30' ,
  },
  {
    children: [
      {
        name: 'Social Media',
        topicID: 'topics_content_socialmedia',
        icon: 'thumbs-up',
        color: 'blue',
        image: 'https://unsplash.com/photos/CNbRsQj8mHQ' ,
      },
      {
        name: 'Blogging',
        topicID: 'topics_content_blogging',
        icon: 'thumbs-up',
        color: 'blue',
        image: 'https://unsplash.com/photos/3GZNPBLImWc' ,
      },
      {
        name: 'Podcasting',
        topicID: 'topics_content_podcasting',
        icon: 'thumbs-up',
        color: 'blue',
        image: 'https://unsplash.com/photos/OaPksPcVp50' ,
      },
      {
        name: 'YouTube',
        topicID: 'topics_content_youtube',
        icon: 'thumbs-up',
        color: 'blue',
        image: 'https://unsplash.com/photos/7y-Fr59_MmI' ,
      },
      {
        name: 'Streaming',
        topicID: 'topics_content_streaming',
        icon: 'thumbs-up',
        color: 'blue',
        image: 'https://unsplash.com/photos/dvrh7Hpuyp4' ,
      },
    ],
    name: 'Content Creators',
    topicID: 'topics_content',
    icon: 'thumbs-up',
    color: 'blue',
    image: 'https://unsplash.com/photos/0eo4e1eh13I' ,
  },
  {
    children: [
      {
        name: 'Politics',
        topicID: 'topics_news_politics',
        icon: 'newspaper',
        color: 'gray100',
        image: 'https://unsplash.com/photos/v0OWc_skg0g' ,
      },
      {
        name: 'Journalism',
        topicID: 'topics_news_journalism',
        icon: 'newspaper',
        color: 'gray100',
        image: 'https://unsplash.com/photos/zAi2Is48-MA' ,
      },
      {
        name: 'Law & Policy',
        topicID: 'topics_news_lawpolicy',
        icon: 'newspaper',
        color: 'gray100',
        image: 'https://unsplash.com/photos/L4YGuSg0fxs' ,
      },
    ],
    name: 'News & Politics',
    topicID: 'topics_news',
    icon: 'newspaper',
    color: 'gray100',
    image: 'https://unsplash.com/photos/Mwuod2cm8g4' ,
  },
  {
    children: [
      {
        name: 'Esports',
        topicID: 'topics_sports_esports',
        icon: 'football-ball',
        color: 'orange',
        image: 'https://unsplash.com/photos/tBG35b1ju2U' ,
      },
      {
        name: 'Football',
        topicID: 'topics_sports_football',
        icon: 'football-ball',
        color: 'orange',
        image: 'https://unsplash.com/photos/-nATH0CrkMU' ,
      },
      {
        name: 'Basketball',
        topicID: 'topics_sports_basketball',
        icon: 'football-ball',
        color: 'orange',
        image: 'https://unsplash.com/photos/nM2WEy42Npg' ,
      },
      {
        name: 'Baseball',
        topicID: 'topics_sports_baseball',
        icon: 'football-ball',
        color: 'orange',
        image: 'https://unsplash.com/photos/FobzAZJGM9M' ,
      },
      {
        name: 'Softball',
        topicID: 'topics_sports_softball',
        icon: 'football-ball',
        color: 'orange',
        image: 'https://unsplash.com/photos/zoWzrCPCa5U' ,
      },
      {
        name: 'Lacrosse',
        topicID: 'topics_sports_lacrosse',
        icon: 'football-ball',
        color: 'orange',
        image: 'https://unsplash.com/photos/O8-sO2GdTMo' ,
      },
      {
        name: 'Auto Racing',
        topicID: 'topics_sports_autoracing',
        icon: 'football-ball',
        color: 'orange',
        image: 'https://unsplash.com/photos/bbYQYZ0Xt_M' ,
      },
      {
        name: 'Hockey',
        topicID: 'topics_sports_hockey',
        icon: 'football-ball',
        color: 'orange',
        image: 'https://unsplash.com/photos/5oZ9uVx7buc' ,
      },
      {
        name: 'Golf',
        topicID: 'topics_sports_golf',
        icon: 'football-ball',
        color: 'orange',
        image: 'https://unsplash.com/photos/wn35CKouahQ' ,
      },
      {
        name: 'MMA',
        topicID: 'topics_sports_mma',
        icon: 'football-ball',
        color: 'orange',
        image: 'https://unsplash.com/photos/I6xpuYm_byM' ,
      },
    ],
    name: 'Sports',
    topicID: 'topics_sports',
    icon: 'football-ball',
    color: 'orange',
    image: 'https://unsplash.com/photos/zmN2bVDFvQ0' ,
  },
  {
    children: [
      {
        name: 'House Flipping',
        topicID: 'topics_realestate_houseflipping',
        icon: 'home',
        color: 'blue',
        image: 'https://unsplash.com/photos/rgJ1J8SDEAY' ,
      },
      {
        name: 'Commercial',
        topicID: 'topics_realestate_commercial',
        icon: 'home',
        color: 'blue',
        image: 'https://unsplash.com/photos/PQUOhz2MOWw' ,
      },
      {
        name: 'Multifamily',
        topicID: 'topics_realestate_multifamily',
        icon: 'home',
        color: 'blue',
        image: 'https://unsplash.com/photos/WCgioEcEVNc' ,
      },
      {
        name: 'Single Family',
        topicID: 'topics_realestate_singlefamily',
        icon: 'home',
        color: 'blue',
        image: 'https://unsplash.com/photos/561igiTyvSk' ,
      },
      {
        name: 'Realtor',
        topicID: 'topics_realestate_realtor',
        icon: 'home',
        color: 'blue',
        image: 'https://unsplash.com/photos/tPX992SVljo' ,
      },
    ],
    name: 'Real Estate',
    topicID: 'topics_realestate',
    icon: 'home',
    color: 'blue',
    image: 'https://unsplash.com/photos/QHDFm084RNk' ,
  },
  {
    children: [
      {
        name: 'Pre-school',
        topicID: 'topics_education_preschool',
        icon: 'graduation-cap',
        color: 'black',
        image: 'https://unsplash.com/photos/YZOVz5f3SBo' ,
      },
      {
        name: 'Elementary',
        topicID: 'topics_education_elementary',
        icon: 'graduation-cap',
        color: 'black',
        image: 'https://unsplash.com/photos/WE_Kv_ZB1l0' ,
      },
      {
        name: 'Middle School',
        topicID: 'topics_education_middleschool',
        icon: 'graduation-cap',
        color: 'black',
        image: 'https://unsplash.com/photos/7DMkvNblkpw' ,
      },
      {
        name: 'High School',
        topicID: 'topics_education_highschool',
        icon: 'graduation-cap',
        color: 'black',
        image: 'https://unsplash.com/photos/JkA4jNmx7mY' ,
      },
      {
        name: 'Undergraduate',
        topicID: 'topics_education_undergraduate',
        icon: 'graduation-cap',
        color: 'black',
        image: 'https://unsplash.com/photos/yL6CrMggt8g' ,
      },
      {
        name: 'Graduate',
        topicID: 'topics_education_graduate',
        icon: 'graduation-cap',
        color: 'black',
        image: 'https://unsplash.com/photos/0oa1jhDLevQ' ,
      },
      {
        name: 'Doctoral Studies',
        topicID: 'topics_education_doctoralstudies',
        icon: 'graduation-cap',
        color: 'black',
        image: 'https://unsplash.com/photos/s9CC2SKySJM' ,
      },
    ],
    name: 'Education',
    topicID: 'topics_education',
    icon: 'graduation-cap',
    color: 'black',
    image: 'https://unsplash.com/photos/HH4WBGNyltc' ,
  },
  {
    children: [
      {
        name: 'Food & Bev',
        topicID: 'topics_industry_foodbev',
        icon: 'cogs',
        color: 'purple',
        image: 'https://unsplash.com/photos/wrPxb-FDp1c' ,
      },
      {
        name: 'E-commerce & Retail',
        topicID: 'topics_industry_ecommerceretail',
        icon: 'cogs',
        color: 'purple',
        image: 'https://unsplash.com/photos/F1I4IN86NiE' ,
      },
      {
        name: 'Construction',
        topicID: 'topics_industry_construction',
        icon: 'cogs',
        color: 'purple',
        image: 'https://unsplash.com/photos/ESZRBtkQ_f8' ,
      },
      {
        name: 'Non-profit',
        topicID: 'topics_industry_nonprofit',
        icon: 'cogs',
        color: 'purple',
        image: 'https://unsplash.com/photos/uXvUpHY5o_4' ,
      },
      {
        name: 'Travel & Hospitality',
        topicID: 'topics_industry_travelhospitality',
        icon: 'cogs',
        color: 'purple',
        image: 'https://unsplash.com/photos/uE2T1tCFsn8' ,
      },
    ],
    name: 'Industry',
    topicID: 'topics_industry',
    icon: 'cogs',
    color: 'purple',
    image: 'https://unsplash.com/photos/-fGqsewtsJY' ,
  },
];

module.exports = {
  topicsList
};
